# github.com/flipped-aurora/gin-vue-admin/server Global Configuration

# mysql connect configuration
# 未初始化之前请勿手动修改数据库信息！！！
# 如果一定要手动初始化请看（https://www.github.com/flipped-aurora/gin-vue-admin/server.com/docs/first）
mysql:
  path: '101.35.136.100:3306'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  db-name: 'admin_gin'
  username: 'admin_gin'
  password: 'k5kBPRFECDrAGPfN'
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false
#  log-zap: true   # 是否使用 zap 来写日志

# jwt configuration
jwt:
  signing-key: 'qmPlus'
  expires-time: 604800
  buffer-time: 86400

# zap logger configuration
zap:
  level: 'debug'
#  level: 'info'
#  format: 'console'
  format: 'json'   # 日志的格式
  prefix: '[admin]'  # 日志的前缀
  director: 'log'  # 日志文件夹
  link-name: 'latest_log'   #生成软链，指向最新日志文件
  show-line: true   # 调用者的文件名和行号注释每条消息
  # "LowercaseLevelEncoder": 小写编码器(默认)  "LowercaseColorLevelEncoder": 小写编码器带颜色
  # "CapitalLevelEncoder":  大写编码器        "CapitalColorLevelEncoder":   大写编码器带颜色
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true   # 是否输出日志到终端

# redis configuration
redis:
  db: 0
  addr: '127.0.0.1:6379'
  password: ''

# email configuration
email:
  to: 'xxx@qq.com'
  port: 465
  from: 'xxx@163.com'
  host: 'smtp.163.com'
  is-ssl: true
  secret: 'xxx'
  nickname: 'test'

# casbin configuration
casbin:
  model-path: './resource/rbac_model.conf'

# system configuration
system:
  env: 'public'  # Change to "develop" to skip authentication for development mode
  addr: 8888
  db-type: 'mysql'
  oss-type: 'local'    # 控制oss选择走本地还是 七牛等其他仓 自行增加其他oss仓可以在 server/utils/upload/upload.go 中 NewOss函数配置
#  use-multipoint: false   # 是否开启单点登录
  use-multipoint: true

# captcha configuration
captcha:
  key-long: 4   # 验证码的长度
  img-width: 240
  img-height: 80



# local configuration
local:
  path: 'uploads/file'

# autocode configuration
autocode:
  transfer-restart: true
  root: ""
  server: /server
  server-api: /api/v1/autocode
  server-initialize: /initialize
  server-model: /model/autocode
  server-request: /model/autocode/request/
  server-router: /router/autocode
  server-service: /service/autocode
  web: /web/src
  web-api: /api
  web-flow: /view
  web-form: /view
  web-table: /view

# qiniu configuration (请自行七牛申请对应的 公钥 私钥 bucket 和 域名地址)
qiniu:
  zone: 'ZoneHuaDong'
  bucket: ''
  img-path: ''
  use-https: false
  access-key: ''
  secret-key: ''
  use-cdn-domains: false


# aliyun oss configuration
aliyun-oss:
  endpoint: 'yourEndpoint'
  access-key-id: 'yourAccessKeyId'
  access-key-secret: 'yourAccessKeySecret'
  bucket-name: 'yourBucketName'
  bucket-url: 'yourBucketUrl'
  base-path: 'yourBasePath'

# tencent cos configuration
tencent-cos:
  bucket: 'xxxxx-10005608'
  region: 'ap-shanghai'
  secret-id: 'xxxxxxxx'
  secret-key: 'xxxxxxxx'
  base-url: 'https://gin.vue.admin'
  path-prefix: 'github.com/flipped-aurora/gin-vue-admin/server'

# excel configuration
excel:
  dir: './resource/excel/'


# timer task db clear table
Timer:
  start: true
  spec: "@daily"  # 定时任务详细配置参考 https://pkg.go.dev/github.com/robfig/cron/v3
  detail: [
    # tableName: 需要清理的表名
    # compareField: 需要比较时间的字段
    # interval: 时间间隔, 具体配置详看 time.ParseDuration() 中字符串表示 且不能为负数
    # 2160h = 24 * 30 * 3 -> 三个月
    { tableName: "sys_operation_records" , compareField: "created_at", interval: "2160h" },
    { tableName: "jwt_blacklists" , compareField: "created_at", interval: "168h" }
    #{ tableName: "log2" , compareField: "created_at", interval: "2160h" }
  ]

